# Generated by Django 3.2.8 on 2022-06-24 09:20
import uuid

from django.db import migrations
from dotenv import load_dotenv
from rest_framework.utils import json

load_dotenv()


def initial_data(apps, schema_editor):
    category_model = apps.get_model('api_categories', 'Category')
    categories = []

    json_data = json.load(open('api_categories/constants/category.json'))
    for category_data in json_data:
        category = category_model(id=uuid.uuid4(),
                                  name=category_data.get('name'),
                                  slug=category_data.get('slug'))
        categories.append(category)

    category_model.objects.bulk_create(categories)


class Migration(migrations.Migration):
    dependencies = [
        ('api_categories', '0002_alter_category_table'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
