# Generated by Django 3.2.8 on 2022-07-05 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='order_product',
        ),
    ]
