# Generated by Django 3.2.8 on 2022-07-15 16:13

from django.db import migrations
from django.db.migrations import RunPython

from api_accounts.constants import RoleData


def initial_data(apps, schema_editor):
    role_model = apps.get_model("api_accounts", "Role")
    roles = []

    for role in RoleData:
        roles.append(role_model(id=role.value['id'], name=role.value['name']))

    role_model.objects.bulk_create(roles)


class Migration(migrations.Migration):
    dependencies = [
        ('api_accounts', '0002_add_role_to_account'),
    ]

    operations = [
        migrations.RunPython(initial_data, RunPython.noop)
    ]
