# Generated by Django 3.2.8 on 2022-07-15 15:42
import json
import os
import uuid

from django.contrib.auth.hashers import make_password
from django.db import migrations

from api_accounts.constants import RoleData


def initial_data(apps, schema_editor):
    account_model = apps.get_model("api_accounts", 'Account')
    user_model = apps.get_model("api_users", 'User')

    json_data = json.load(
        open('api_users/constants/user.json', encoding="utf8"))
    default_user_password = make_password(os.getenv('DEFAULT_USER_PASSWORD'))
    user_role = RoleData.USER.value.get("id")

    users = []

    for user_data in json_data:
        account_data = user_data['account']
        # random uuid.uuid4()
        account = account_model(id=uuid.uuid4(),
                                username=account_data['username'],
                                password=default_user_password,
                                role_id=user_role)
        account.save()
        user_data['account'] = account

        users.append(user_model(**user_data))

    user_model.objects.bulk_create(users)


class Migration(migrations.Migration):
    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
