# Generated by Django 3.2.8 on 2022-06-29 10:56
import os
import uuid

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.migrations import RunPython
from rest_framework.utils import json

from api_accounts.constants import RoleData


def initial_data(apps, schema_editor):
    account_model = apps.get_model('api_accounts', 'Account')
    user_model = apps.get_model('api_users', 'User')
    json_data = json.load(open('api_users/constants/admin.json', encoding="utf8"))
    admin_role = RoleData.ADMIN.value.get('id')
    default_admin_password = os.getenv('DEFAULT_ADMIN_PASSWORD')
    admins = []
    for admin_data in json_data:
        account_data = admin_data['account']
        account = account_model(id=uuid.uuid4(),
                                username=account_data['username'],
                                password=make_password(default_admin_password),
                                role_id=admin_role)

        account.save()

        admin_data['account'] = account
        admins.append(user_model(**admin_data))

    user_model.objects.bulk_create(admins)


class Migration(migrations.Migration):
    dependencies = [
        ('api_users', '0002_migrate_user_data'),
    ]

    operations = [
        migrations.RunPython(initial_data, RunPython.noop)
    ]
