# Generated by Django 3.2.8 on 2022-12-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_migrate_admin_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
