# Generated by Django 3.2.8 on 2022-06-24 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
