# Generated by Django 3.2.8 on 2022-06-24 10:08
import uuid

from django.db import migrations
from rest_framework.utils import json

from api_categories.services import CategoryService


def initial_data(apps, schema_editor):
    product_model = apps.get_model('api_products', 'Product')
    products = []
    json_data = json.load(open('api_products/constants/product.json', encoding="utf-8"))

    for product_data in json_data:
        category_id = CategoryService.get_category_id_by_name(
            product_data.get('category'))
        product = product_model(id=uuid.uuid4(),
                                name=product_data.get('name'),
                                slug=product_data.get('slug'),
                                description=product_data.get('description'),
                                price=product_data.get('price'),
                                image=product_data.get('image'),
                                thumbnail=product_data.get('thumbnail'),
                                category_id=category_id
                                )
        products.append(product)
    product_model.objects.bulk_create(products)


class Migration(migrations.Migration):
    dependencies = [
        ('api_products', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
